# Generated by Django 4.2.6 on 2023-10-15 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('counter_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('serivice_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_counters', models.PositiveIntegerField()),
                ('services', models.JSONField()),
                ('service_per_counter', models.JSONField()),
                ('counter_status', models.JSONField()),
                ('token_limit_per_counter', models.PositiveBigIntegerField()),
                ('service_modes', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.counter')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.service')),
            ],
        ),
    ]
