# Generated by Django 4.2.6 on 2023-10-16 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='serivice_name',
            new_name='service_name',
        ),
        migrations.AddField(
            model_name='counter',
            name='service_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.service'),
            preserve_default=False,
        ),
    ]
