# Generated by Django 4.2.6 on 2023-10-16 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_serivice_name_service_service_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='token',
            new_name='id',
        ),
    ]
